#!/bin/sh

#docker run -p 8080:8080 -t springio/gs-spring-boot-docker

docker run -e "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n" -p 8080:8080 -p 5005:5005 -t springio/gs-spring-boot-docker
